spring:
  application:
    name: microservices-template
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full
