apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-template-deployment
spec:
  selector:
    matchLabels:
      app: microservices-template
  replicas: 2
  template:
    metadata:
      labels:
        app: microservices-template
    spec:
      containers:
      - name: microservices-template
        image: colinbut/microservices-template:1.0.0-SNAPSHOT
        ports:
        - containerPort: 8080